### ISSUE TITLE
Evaluation of GAN

### ISSUE THREAD

**Issue by vinthony** [ta-oyama/Semantic-Segmentation-using-Adversarial-Networks#2]
Hi, thanks for your implementation.

Have you run the experiments in the original paper? 

Are there any improvements by using GAN in semantic segmentation tasks? 

GAN often generate weird results which seem like "ground truth", but poorly in the evaluation.

**Comment by oyam** [comment]
I experimented with FCN-VGG16 instead of DilatedNet. However, accuracy has not been improved by using GAN yet.

**Comment by vinthony** [comment]
Thanks for your reply :)
